export const burgerMenu = (images) => {
    return [
        {name: 'Opinión', link: '/opinion/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/opinion', 
    sections: [
    { name: 'Editorial', link: '/opinion/editorial/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/opinion/editorial', },
    { name: 'Columnistas', link: '/opinion/columnistas/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/opinion/columnistas', },
    { name: 'Caricaturistas', link: '/opinion/caricaturistas/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/opinion/caricaturistas', },
    { name: 'Lectores', link: '/opinion/lectores/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/opinion/lectores', 
    sections:[
    { name: 'Antieditorial', link: '/opinion/lectores/antieditorial/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa', linkOriginal: '/opinion/lectores/antieditorial'},
    { name: 'Cartas', link: '/opinion/lectores/cartas/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa', linkOriginal: '/opinion/lectores/cartas'},
    { name: 'Columnas del Lector', link: '/opinion/lectores/columnas-del-lector/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa', linkOriginal: '/opinion/lectores/columnas-del-lector'},
    { name: 'Caricaturas del Lector', link: '/opinion/lectores/caricaturas-del-lector/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa', linkOriginal: '/opinion/lectores/caricaturas-del-lector'},],},],  },
        {name: 'Judicial', link: '/judicial/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/judicial',   },
        {name: 'Política', link: '/politica/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/politica',   },
        {name: 'Investigación', link: '/investigacion/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/investigacion',   },
        {name: 'Colombia', link: '/colombia/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/colombia', 
    sections: [
    { name: 'Medellín', link: '/colombia/medellin/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/colombia/medellin', },
    { name: 'Cali', link: '/colombia/cali/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/colombia/cali', },
    { name: 'Barranquilla', link: '/colombia/barranquilla/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/colombia/barranquilla', },
    { name: 'Cartagena', link: '/colombia/cartagena/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/colombia/cartagena', },
    { name: 'Cundinamarca', link: '/colombia/cundinamarca/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/colombia/cundinamarca', },
    { name: 'Más regiones', link: '/colombia/mas-regiones/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/colombia/mas-regiones', },],  },
        {name: 'Bogotá', link: '/bogota/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/bogota',   },
        {name: 'Mundo', link: '/mundo/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/mundo', 
    sections: [
    { name: 'América', link: '/mundo/america/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/mundo/america', },
    { name: 'Europa', link: '/mundo/europa/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/mundo/europa', },
    { name: 'Más países', link: '/mundo/mas-paises/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/mundo/mas-paises', },],  },
        {name: 'Economía', link: '/economia/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/economia', 
    sections: [
    { name: 'Finanzas personales', link: '/economia/finanzas-personales/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/economia/finanzas-personales', },
    { name: 'Macroeconomía', link: '/economia/macroeconomia/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/economia/macroeconomia', },
    { name: 'Empresas', link: '/economia/empresas/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/economia/empresas', },
    { name: 'Emprendimiento y Liderazgo', link: '/economia/emprendimiento-y-liderazgo/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/economia/emprendimiento-y-liderazgo', },],  },
        {name: 'Tecnología', link: '/tecnologia/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/tecnologia', 
    sections: [
    { name: 'Gadgets y Apps', link: '/tecnologia/gadgets-y-apps/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/tecnologia/gadgets-y-apps', },],  },
        {name: 'Ciencia', link: '/ciencia/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/ciencia',   },
        {name: 'Ambiente', link: '/ambiente/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/ambiente', 
    sections: [
    { name: 'Amazonas', link: '/ambiente/amazonas/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/ambiente/amazonas', },
    { name: 'BIBO', link: '/ambiente/bibo/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/ambiente/bibo', },
    { name: 'Blog El Río', link: '/ambiente/blog-el-rio/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/ambiente/blog-el-rio', },],  },
        {name: 'Salud', link: '/salud/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/salud',   },
        {name: 'Educación', link: '/educacion/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/educacion',   },
        {name: 'Entretenimiento', link: '/entretenimiento/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/entretenimiento', 
    sections: [
    { name: 'Música', link: '/entretenimiento/musica/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/entretenimiento/musica', },
    { name: 'Cine y TV', link: '/entretenimiento/cine-y-tv/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/entretenimiento/cine-y-tv', },
    { name: 'Gente', link: '/entretenimiento/gente/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/entretenimiento/gente', },
    { name: 'Horóscopo', link: '/entretenimiento/horoscopo/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/entretenimiento/horoscopo', },
    { name: 'Tarot de Mavé', link: '/entretenimiento/tarot-de-mave/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/entretenimiento/tarot-de-mave', },],  },
        {name: 'Deportes', link: '/deportes/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/deportes', 
    sections: [
    { name: 'Fútbol Colombiano', link: '/deportes/futbol-colombiano/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/deportes/futbol-colombiano', 
    sections:[
    { name: 'Millonarios', link: '/deportes/futbol-colombiano/millonarios/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa', linkOriginal: '/deportes/futbol-colombiano/millonarios'},
    { name: 'Santa Fe', link: '/deportes/futbol-colombiano/santa-fe/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa', linkOriginal: '/deportes/futbol-colombiano/santa-fe'},
    { name: 'América de Cali', link: '/deportes/futbol-colombiano/america-de-cali/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa', linkOriginal: '/deportes/futbol-colombiano/america-de-cali'},
    { name: 'Atlético Nacional', link: '/deportes/futbol-colombiano/atletico-nacional/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa', linkOriginal: '/deportes/futbol-colombiano/atletico-nacional'},
    { name: 'Júnior', link: '/deportes/futbol-colombiano/junior-fc/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa', linkOriginal: '/deportes/futbol-colombiano/junior-fc'},
    { name: 'Otros equipos', link: '/deportes/futbol-colombiano/otros-equipos/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa', linkOriginal: '/deportes/futbol-colombiano/otros-equipos'},],},
    { name: 'Selección Colombia', link: '/deportes/seleccion-colombia/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/deportes/seleccion-colombia', },
    { name: 'Fútbol mundial', link: '/deportes/futbol-mundial/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/deportes/futbol-mundial', },
    { name: 'Ciclismo', link: '/deportes/ciclismo/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/deportes/ciclismo', },
    { name: 'Más deportes', link: '/deportes/mas-deportes/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/deportes/mas-deportes', },
    { name: 'Analistas', link: '/deportes/analistas/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/deportes/analistas', },],  },
        {name: 'Especiales', link: '/especiales/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/especiales',   },
        {name: 'Colecciones', link: '/colecciones/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/colecciones',   },
        {name: 'Contenido Patrocinado', link: '/contenido-patrocinado/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/contenido-patrocinado',   },
        {name: 'Reportajes', link: '/reportajes/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/reportajes',   },
        {name: 'Marcas Transversales', link: '/marcas-transversales/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/marcas-transversales',   },
        {name: 'Colombia +20', link: '/colombia-20/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/colombia-20', 
    sections: [
    { name: 'Conflicto', link: '/colombia-20/conflicto/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/colombia-20/conflicto', },
    { name: 'JEP y Desaparecidos', link: '/colombia-20/jep-y-desaparecidos/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/colombia-20/jep-y-desaparecidos', },
    { name: 'Analistas', link: '/colombia-20/analistas/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/colombia-20/analistas', },
    { name: 'Paz y Memoria', link: '/colombia-20/paz-y-memoria/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/colombia-20/paz-y-memoria', },],  gray: true, image: images['/colombia-20'].image, imageMobile: images['/colombia-20'].imageMobile },
        {name: 'El magazín cultural', link: '/el-magazin-cultural/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/el-magazin-cultural', 
    sections: [
    { name: 'La suma de las voces', link: '/el-magazin-cultural/la-suma-de-las-voces/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/el-magazin-cultural/la-suma-de-las-voces', },],  gray: true, image: images['/el-magazin-cultural'].image, imageMobile: images['/el-magazin-cultural'].imageMobile },
        {name: 'Impacto Mujer', link: '/impacto-mujer/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/impacto-mujer',   gray: true, image: images['/impacto-mujer'].image, imageMobile: images['/impacto-mujer'].imageMobile },
        {name: 'Cromos', link: '/cromos/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/cromos', 
    sections: [
    { name: 'Gastronomía', link: '/cromos/gastronomia/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/cromos/gastronomia', },
    { name: 'Maternidad y Bienestar', link: '/cromos/maternidad-y-bienestar/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/cromos/maternidad-y-bienestar', },
    { name: 'Columnistas', link: '/cromos/columnistas/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/cromos/columnistas', },
    { name: 'Estilo de vida', link: '/cromos/estilo-de-vida/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/cromos/estilo-de-vida', },
    { name: 'Astrología', link: '/cromos/astrologia/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/cromos/astrologia', },
    { name: 'Vida Social', link: '/cromos/vida-social/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/cromos/vida-social', },
    { name: 'Moda', link: '/cromos/moda/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/cromos/moda', },],  gray: true, image: images['/cromos'].image, imageMobile: images['/cromos'].imageMobile },
        {name: 'Autos', link: '/autos/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/autos',   gray: true, image: images['/autos'].image, imageMobile: images['/autos'].imageMobile },
        {name: 'Revista Vea', link: '/revista-vea/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/revista-vea', 
    sections: [
    { name: 'Celebridades', link: '/revista-vea/celebridades/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/revista-vea/celebridades', },
    { name: 'Lo más hit', link: '/revista-vea/lo-mas-hit/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/revista-vea/lo-mas-hit', },
    { name: 'Véanlos', link: '/revista-vea/veanlos/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/revista-vea/veanlos', },
    { name: 'Historias de vida', link: '/revista-vea/historias-de-vida/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/revista-vea/historias-de-vida', },
    { name: 'Los astros y las estrellas', link: '/revista-vea/los-astros-y-las-estrellas/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/revista-vea/los-astros-y-las-estrellas', },],  gray: true, image: images['/revista-vea'].image, imageMobile: images['/revista-vea'].imageMobile },
        {name: 'Turismo', link: '/turismo/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/turismo',   gray: true, image: images['/turismo'].image, imageMobile: images['/turismo'].imageMobile },
        {name: 'Gastronomía y Recetas', link: '/gastronomia-y-recetas/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/gastronomia-y-recetas',   gray: true, image: images['/gastronomia-y-recetas'].image, imageMobile: images['/gastronomia-y-recetas'].imageMobile },
        {name: 'Desaparecidos', link: '/desaparecidos-colombia/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/desaparecidos-colombia',   gray: true, image: images['/desaparecidos-colombia'].image, imageMobile: images['/desaparecidos-colombia'].imageMobile },
        {name: 'Servicios Aliados', link: null,linkOriginal: null, outside: true,   },
        {name: 'Idiomas', link: null,linkOriginal: null, outside: true, 
    sections: [
    { name: 'Inglés', link: 'https://idiomas.elespectador.com/es/gymglish', linkOriginal: null, outside: true, },
    { name: 'Francés', link: 'https://idiomas.elespectador.com/es/frantastique', linkOriginal: null, outside: true, },
    { name: 'Alemán', link: 'https://idiomas.elespectador.com/es/wunderbla', linkOriginal: null, outside: true, },
    { name: 'Spanish', link: 'https://idiomas.elespectador.com/en/hotel-borbollon', linkOriginal: null, outside: true, },],  },
        {name: 'Descuentos', link: 'https://descuentos.elespectador.com',linkOriginal: null, outside: true,   },
        {name: 'Director técnico', link: 'https://directortecnico.elespectador.com',linkOriginal: null, outside: true,   },
        {name: 'Mas en el Espectador', link: '/mas-en-el-espectador/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/mas-en-el-espectador',   },
        {name: 'Video', link: '/video/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/video',   },
        {name: 'El Carrito', link: '/el-carrito/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/el-carrito',   },
        {name: 'Historias Visuales', link: '/historias-visuales/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/historias-visuales',   },
        {name: 'Pasatiempos', link: 'https://pasatiempos.elespectador.com',linkOriginal: null, outside: true,   },
        {name: 'Newsletters', link: '/newsletters/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/newsletters',   },
        {name: 'Blogs', link: 'https://blogs.elespectador.com',linkOriginal: null, outside: true,   },
        {name: 'Actualidad', link: '/actualidad/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/actualidad',   },
    ];
    };

    export const main = [
        {name: 'Opinión', link: 'https://www.elespectador.com/opinion/'},
        {name: 'Colombia', link: 'https://www.elespectador.com/colombia/'},
        {name: 'Mundo', link: 'https://www.elespectador.com/mundo/'},
        {name: 'El Magazín Cultural', link: 'https://www.elespectador.com/el-magazin-cultural/'},
        {name: 'Deportes', link: 'https://www.elespectador.com/deportes/'},
        {name: 'Autos', link: 'https://www.elespectador.com/autos/'},
        {name: 'Especiales', link: 'https://www.elespectador.com/especiales/'},
        {name: 'Cromos', link: 'https://www.elespectador.com/cromos/'},
        {name: 'Revista Vea', link: 'https://www.elespectador.com/revista-vea/'},
    ];

    export const footerSections = (images) => {
        return [
            {name: 'Opinión', link: 'https://www.elespectador.com/opinion/' },
            {name: 'Judicial', link: 'https://www.elespectador.com/judicial/' },
            {name: 'Política', link: 'https://www.elespectador.com/politica/' },
            {name: 'Investigación', link: 'https://www.elespectador.com/investigacion/' },
            {name: 'Colombia', link: 'https://www.elespectador.com/colombia/' },
            {name: 'Bogotá', link: 'https://www.elespectador.com/bogota/' },
            {name: 'Mundo', link: 'https://www.elespectador.com/mundo/' },
            {name: 'Economía', link: 'https://www.elespectador.com/economia/' },
            {name: 'Tecnología', link: 'https://www.elespectador.com/tecnologia/' },
            {name: 'Ciencia', link: 'https://www.elespectador.com/ciencia/' },
            {name: 'Ambiente', link: 'https://www.elespectador.com/ambiente/' },
            {name: 'Salud', link: 'https://www.elespectador.com/salud/' },
            {name: 'Educación', link: 'https://www.elespectador.com/educacion/' },
            {name: 'Entretenimiento', link: 'https://www.elespectador.com/entretenimiento/' },
            {name: 'Deportes', link: 'https://www.elespectador.com/deportes/' },
            {name: 'Video', link: 'https://www.elespectador.com/video/' },
            {name: 'Especiales', link: 'https://www.elespectador.com/especiales/' },
            {name: 'Colecciones', link: 'https://www.elespectador.com/colecciones/' },
            {name: 'Contenido Patrocinado', link: 'https://www.elespectador.com/contenido-patrocinado/' },
            {name: 'Reportajes', link: 'https://www.elespectador.com/reportajes/' },
            {name: 'Historias Visuales', link: 'https://www.elespectador.com/historias-visuales/' },
            {name: 'Pasatiempos', link: 'https://pasatiempos.elespectador.com', outside: true },
            {name: 'Blogs', link: 'https://blogs.elespectador.com', outside: true },
            {name: 'Actualidad', link: 'https://www.elespectador.com/actualidad/' },
            {name: 'El Carrito', link: 'https://www.elespectador.com/el-carrito/' },
            {name: 'El magazín cultural', link: 'https://www.elespectador.com/el-magazin-cultural/' , gray: true, image: images['/el-magazin-cultural'].image, imageMobile: images['/el-magazin-cultural'].imageMobile},
            {name: 'Colombia +20', link: 'https://www.elespectador.com/colombia-20/' , gray: true, image: images['/colombia-20'].image, imageMobile: images['/colombia-20'].imageMobile},
            {name: 'Impacto Mujer', link: 'https://www.elespectador.com/impacto-mujer/' , gray: true, image: images['/impacto-mujer'].image, imageMobile: images['/impacto-mujer'].imageMobile},
            {name: 'Cromos', link: 'https://www.elespectador.com/cromos/' , gray: true, image: images['/cromos'].image, imageMobile: images['/cromos'].imageMobile},
            {name: 'Autos', link: 'https://www.elespectador.com/autos/' , gray: true, image: images['/autos'].image, imageMobile: images['/autos'].imageMobile},
            {name: 'Revista Vea', link: 'https://www.elespectador.com/revista-vea/' , gray: true, image: images['/revista-vea'].image, imageMobile: images['/revista-vea'].imageMobile},
            {name: 'Turismo', link: 'https://www.elespectador.com/turismo/' , gray: true, image: images['/turismo'].image, imageMobile: images['/turismo'].imageMobile},
            {name: 'Gastronomía y Recetas', link: 'https://www.elespectador.com/gastronomia-y-recetas/' , gray: true, image: images['/gastronomia-y-recetas'].image, imageMobile: images['/gastronomia-y-recetas'].imageMobile},
            {name: 'Desaparecidos', link: 'https://www.elespectador.com/desaparecidos-colombia/' , gray: true, image: images['/desaparecidos-colombia'].image, imageMobile: images['/desaparecidos-colombia'].imageMobile},
        ];
        };