export const burgerMenu = (images) => {
    return [
        {name: 'Opinión', link: 'https://www.elespectador.com/opinion/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/opinion', outside: true ,
    sections: [
    { name: 'Editorial', link: 'https://www.elespectador.com/opinion/editorial/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/opinion/editorial', outside: true  },
    { name: 'Columnistas', link: 'https://www.elespectador.com/opinion/columnistas/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/opinion/columnistas', outside: true },
    { name: 'Caricaturistas', link: 'https://www.elespectador.com/opinion/caricaturistas/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/opinion/caricaturistas',outside: true  },
    { name: 'Lectores', link: 'https://www.elespectador.com/opinion/lectores/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/opinion/lectores', outside: true ,
    sections:[
    { name: 'Antieditorial', link: 'https://www.elespectador.com/opinion/lectores/antieditorial/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa', linkOriginal: '/opinion/lectores/antieditorial', outside: true },
    { name: 'Cartas', link: 'https://www.elespectador.com/opinion/lectores/cartas/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa', linkOriginal: '/opinion/lectores/cartas' , outside: true },
    { name: 'Columnas del lector', link: 'https://www.elespectador.com/opinion/lectores/columnas-del-lector/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa', linkOriginal: '/opinion/lectores/columnas-del-lector' },
    { name: 'Caricaturas del lector', link: 'https://www.elespectador.com/opinion/lectores/caricaturas-del-lector/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa', linkOriginal: '/opinion/lectores/caricaturas-del-lector' , outside: true },],},],   },
        {name: 'Judicial', link: 'https://www.elespectador.com/judicial/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/judicial', outside: true     },
        {name: 'Política', link: 'https://www.elespectador.com/politica/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/politica', outside: true, 
    sections: [
    { name: 'Elecciones 2022', link: 'https://www.elespectador.com/politica/elecciones-colombia-2022/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/politica/elecciones-colombia-2022', outside: true  },],   },
        {name: 'Investigación', link: 'https://www.elespectador.com/investigacion/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/investigacion', outside: true     },
        {name: 'Colombia', link: 'https://www.elespectador.com/colombia/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/colombia', outside: true,  
    sections: [
    { name: 'Medellín', link: 'https://www.elespectador.com/colombia/medellin/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/colombia/medellin', outside: true  },
    { name: 'Cali', link: 'https://www.elespectador.com/colombia/cali/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/colombia/cali', outside: true },
    { name: 'Barranquilla', link: 'https://www.elespectador.com/colombia/barranquilla/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/colombia/barranquilla', outside: true  },
    { name: 'Cartagena', link: 'https://www.elespectador.com/colombia/cartagena/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/colombia/cartagena', outside: true },
    { name: 'Cundinamarca', link: 'https://www.elespectador.com/colombia/cundinamarca/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/colombia/cundinamarca', outside: true  },
    { name: 'Más regiones', link: 'https://www.elespectador.com/colombia/mas-regiones/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/colombia/mas-regiones', outside: true  },],   },
        {name: 'Bogotá', link: 'https://www.elespectador.com/bogota/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/bogota', outside: true    },
        {name: 'Mundo', link: 'https://www.elespectador.com/mundo/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/mundo', outside: true, 
    sections: [
    { name: 'América', link: 'https://www.elespectador.com/mundo/america/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/mundo/america', outside: true  },
    { name: 'Europa', link: 'https://www.elespectador.com/mundo/europa/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/mundo/europa', outside: true  },
    { name: 'Más países', link: 'https://www.elespectador.com/mundo/mas-paises/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/mundo/mas-paises', outside: true  },],   },
        {name: 'Economía', link: 'https://www.elespectador.com/economia/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/economia', outside: true,  
    sections: [
    { name: 'Finanzas personales', link: 'https://www.elespectador.com/economia/finanzas-personales/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/economia/finanzas-personales', outside: true  },
    { name: 'Macroeconomía', link: 'https://www.elespectador.com/economia/macroeconomia/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/economia/macroeconomia', outside: true  },
    { name: 'Empresas', link: 'https://www.elespectador.com/economia/empresas/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/economia/empresas', outside: true },
    { name: 'Emprendimiento y liderazgo', link: 'https://www.elespectador.com/economia/emprendimiento-y-liderazgo/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/economia/emprendimiento-y-liderazgo', outside: true  },],   },
        {name: 'Tecnología', link: 'https://www.elespectador.com/tecnologia/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/tecnologia', outside: true, 
    sections: [
    { name: 'Gadgets y apps', link: 'https://www.elespectador.com/tecnologia/gadgets-y-apps/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/tecnologia/gadgets-y-apps', outside: true },],   },
        {name: 'Ciencia', link: 'https://www.elespectador.com/ciencia/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/ciencia', outside: true    },
        {name: 'Ambiente', link: 'https://www.elespectador.com/ambiente/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/ambiente', outside: true, 
    sections: [
    { name: 'Amazonas', link: 'https://www.elespectador.com/ambiente/amazonas/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/ambiente/amazonas', outside: true  },
    { name: 'BIBO', link: 'https://www.elespectador.com/ambiente/bibo/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/ambiente/bibo', },
    { name: 'Blog el río', link: 'https://www.elespectador.com/ambiente/blog-el-rio/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/ambiente/blog-el-rio', outside: true  },],   },
        {name: 'Salud', link: 'https://www.elespectador.com/salud/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/salud', outside: true    },
        {name: 'Educación', link: 'https://www.elespectador.com/educacion/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/educacion', outside: true    },
        {name: 'Entretenimiento', link: 'https://www.elespectador.com/entretenimiento/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/entretenimiento',  outside: true, 
    sections: [
    { name: 'Música', link: 'https://www.elespectador.com/entretenimiento/musica/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/entretenimiento/musica', outside: true  },
    { name: 'Cine y TV', link: 'https://www.elespectador.com/entretenimiento/cine-y-tv/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/entretenimiento/cine-y-tv', outside: true  },
    { name: 'Gente', link: 'https://www.elespectador.com/entretenimiento/gente/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/entretenimiento/gente', outside: true  },
    { name: 'Horóscopo', link: 'https://www.elespectador.com/entretenimiento/horoscopo/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/entretenimiento/horoscopo', outside: true  },
    { name: 'Tarot de mavé', link: 'https://www.elespectador.com/entretenimiento/tarot-de-mave/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/entretenimiento/tarot-de-mave', outside: true },],   },
        {name: 'Deportes', link: 'https://www.elespectador.com/deportes/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/deportes', outside: true, 
    sections: [
    { name: 'Fútbol colombiano', link: 'https://www.elespectador.com/deportes/futbol-colombiano/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/deportes/futbol-colombiano', outside: true, 
    sections:[
    { name: 'Millonarios', link: 'https://www.elespectador.com/deportes/futbol-colombiano/millonarios/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa', linkOriginal: '/deportes/futbol-colombiano/millonarios' , outside: true },
    { name: 'Santa Fe', link: 'https://www.elespectador.com/deportes/futbol-colombiano/santa-fe/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa', linkOriginal: '/deportes/futbol-colombiano/santa-fe' , outside: true },
    { name: 'América de Cali', link: 'https://www.elespectador.com/deportes/futbol-colombiano/america-de-cali/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa', linkOriginal: '/deportes/futbol-colombiano/america-de-cali' , outside: true },
    { name: 'Atlético Nacional', link: 'https://www.elespectador.com/deportes/futbol-colombiano/atletico-nacional/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa', linkOriginal: '/deportes/futbol-colombiano/atletico-nacional' , outside: true },
    { name: 'Júnior', link: 'https://www.elespectador.com/deportes/futbol-colombiano/junior-fc/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa', linkOriginal: '/deportes/futbol-colombiano/junior-fc' , outside: true },
    { name: 'Otros equipos', link: 'https://www.elespectador.com/deportes/futbol-colombiano/otros-equipos/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa', linkOriginal: '/deportes/futbol-colombiano/otros-equipos', outside: true },],},
    { name: 'Selección Colombia', link: 'https://www.elespectador.com/deportes/seleccion-colombia/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/deportes/seleccion-colombia',outside: true },
    { name: 'Fútbol mundial', link: 'https://www.elespectador.com/deportes/futbol-mundial/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/deportes/futbol-mundial', outside: true},
    { name: 'Ciclismo', link: 'https://www.elespectador.com/deportes/ciclismo/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/deportes/ciclismo', outside: true},
    { name: 'Más deportes', link: 'https://www.elespectador.com/deportes/mas-deportes/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/deportes/mas-deportes',outside: true },
    { name: 'Analistas', link: 'https://www.elespectador.com/deportes/analistas/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/deportes/analistas', outside: true},],   },
        {name: 'Especiales', link: 'https://www.elespectador.com/especiales/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/especiales',  outside: true  },
        {name: 'Colecciones', link: 'https://www.elespectador.com/colecciones/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/colecciones',    },
        {name: 'Contenido patrocinado', link: 'https://www.elespectador.com/contenido-patrocinado/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/contenido-patrocinado',outside: true   },
        {name: 'Reportajes', link: 'https://www.elespectador.com/reportajes/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/reportajes',outside: true    },
        {name: 'Marcas Transversales', link: null,linkOriginal: null, outside: true,  titular: true  },
        {name: 'Colombia +20', link: 'https://www.elespectador.com/colombia-20/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/colombia-20', outside: true, 
    sections: [
    { name: 'Conflicto', link: 'https://www.elespectador.com/colombia-20/conflicto/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/colombia-20/conflicto',outside: true },
    { name: 'JEP y desaparecidos', link: 'https://www.elespectador.com/colombia-20/jep-y-desaparecidos/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/colombia-20/jep-y-desaparecidos',outside: true },
    { name: 'Analistas', link: 'https://www.elespectador.com/colombia-20/analistas/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/colombia-20/analistas',outside: true },
    { name: 'Paz y memoria', link: 'https://www.elespectador.com/colombia-20/paz-y-memoria/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/colombia-20/paz-y-memoria', },],   gray: true, image: images['/colombia-20'].image, outside: true }, 
        {name: 'El Magazín Cultural', link: 'https://www.elespectador.com/el-magazin-cultural/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/el-magazin-cultural', outside: true, 
    sections: [
    { name: 'La suma de las voces', link: 'https://www.elespectador.com/el-magazin-cultural/la-suma-de-las-voces/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/el-magazin-cultural/la-suma-de-las-voces', },],   gray: true, image: images['/el-magazin-cultural'].image, outside: true},
        {name: 'Impacto mujer', link: 'https://www.elespectador.com/impacto-mujer/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/impacto-mujer',    gray: true, image: images['/impacto-mujer'].image, outside: true },
        {name: 'Cromos', link: 'https://www.elespectador.com/cromos/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/cromos', outside: true, 
    sections: [
    { name: 'Gastronomía', link: 'https://www.elespectador.com/cromos/gastronomia/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/cromos/gastronomia', outside: true},
    { name: 'Maternidad y bienestar', link: 'https://www.elespectador.com/cromos/maternidad-y-bienestar/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/cromos/maternidad-y-bienestar', outside: true },
    { name: 'Columnistas', link: 'https://www.elespectador.com/cromos/columnistas/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/cromos/columnistas', outside: true},
    { name: 'Estilo de vida', link: 'https://www.elespectador.com/cromos/estilo-de-vida/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/cromos/estilo-de-vida',outside: true },
    { name: 'Astrología', link: 'https://www.elespectador.com/cromos/astrologia/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/cromos/astrologia', outside: true },
    { name: 'Vida social', link: 'https://www.elespectador.com/cromos/vida-social/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/cromos/vida-social', outside: true },
    { name: 'Moda', link: 'https://www.elespectador.com/cromos/moda/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/cromos/moda', },],   gray: true, image: images['/cromos'].image, outside: true },
        {name: 'Autos', link: 'https://www.elespectador.com/autos/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/autos',    gray: true, image: images['/autos'].image, outside: true },
        {name: 'Revista Vea', link: 'https://www.elespectador.com/revista-vea/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/revista-vea', outside: true,
    sections: [
    { name: 'Celebridades', link: 'https://www.elespectador.com/revista-vea/celebridades/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/revista-vea/celebridades', outside: true },
    { name: 'Lo más hit', link: 'https://www.elespectador.com/revista-vea/lo-mas-hit/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/revista-vea/lo-mas-hit', outside: true },
    { name: 'Véanlos', link: 'https://www.elespectador.com/revista-vea/veanlos/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/revista-vea/veanlos', outside: true},
    { name: 'Historias de vida', link: 'https://www.elespectador.com/revista-vea/historias-de-vida/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/revista-vea/historias-de-vida', },
    { name: 'Los astros y las estrellas', link: 'https://www.elespectador.com/revista-vea/los-astros-y-las-estrellas/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/revista-vea/los-astros-y-las-estrellas', },],   gray: true, image: images['/revista-vea'].image, outside: true },
        {name: 'Turismo', link: 'https://www.elespectador.com/turismo/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/turismo',    gray: true, image: images['/turismo'].image, outside: true },
        {name: 'Gastronomía y recetas', link: 'https://www.elespectador.com/gastronomia-y-recetas/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/gastronomia-y-recetas',    gray: true, image: images['/gastronomia-y-recetas'].image, outside: true },
        {name: 'Desaparecidos', link: 'https://www.elespectador.com/desaparecidos-colombia/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/desaparecidos-colombia',    gray: true, image: images['/desaparecidos-colombia'].image, outside: true },
        {name: 'Mas en el Espectador', link: null,linkOriginal: null, outside: true,  titular: true  },
        {name: 'Video', link: 'https://www.elespectador.com/video/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/video', outside: true   },
        {name: 'El Carrito', link: 'https://www.elespectador.com/el-carrito/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/el-carrito', outside: true   },
        {name: 'Historias visuales', link: 'https://www.elespectador.com/historias-visuales/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/historias-visuales',outside: true    },
        {name: 'Pasatiempos', link: 'https://pasatiempos.elespectador.com',linkOriginal: null, outside: true,    },
        {name: 'Newsletters', link: 'https://www.elespectador.com/newsletters/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/newsletters', outside: true   },
        {name: 'Blogs', link: 'https://blogs.elespectador.com',linkOriginal: null, outside: true,    },
        {name: 'Actualidad', link: 'https://www.elespectador.com/actualidad/?utm_source=interno&utm_medium=boton&utm_campaign=menu_hamburguesa&utm_content=boton_menu_hamburguesa' , linkOriginal: '/actualidad',  outside: true  },
        {name: 'Servicios Aliados', link: null,linkOriginal: null, outside: true,  titular: true  },
        {name: 'Idiomas', link: null,linkOriginal: null, outside: true, 
    sections: [
    { name: 'Inglés', link: 'https://idiomas.elespectador.com/es/gymglish', linkOriginal: null, outside: true, },
    { name: 'Francés', link: 'https://idiomas.elespectador.com/es/frantastique', linkOriginal: null, outside: true, },
    { name: 'Alemán', link: 'https://idiomas.elespectador.com/es/wunderbla', linkOriginal: null, outside: true, },
    { name: 'Spanish', link: 'https://idiomas.elespectador.com/en/hotel-borbollon', linkOriginal: null, outside: true, },],   },
        {name: 'Descuentos', link: 'https://descuentos.elespectador.com',linkOriginal: null, outside: true,    },
        {name: 'Director técnico', link: 'https://directortecnico.elespectador.com',linkOriginal: null, outside: true,    },
    ];
    };

    export const main = [
        {name: 'Opinión', link: 'https://www.elespectador.com/opinion/',outside: true},
        {name: 'Colombia', link: 'https://www.elespectador.com/colombia/' ,outside: true},
        {name: 'Mundo', link: 'https://www.elespectador.com/mundo/'},
        {name: 'El Magazín Cultural', link: 'https://www.elespectador.com/el-magazin-cultural/'},
        {name: 'Deportes', link: 'https://www.elespectador.com/deportes/'},
        {name: 'Autos', link: 'https://www.elespectador.com/autos/'},
        {name: 'Especiales', link: 'https://www.elespectador.com/especiales/'},
        {name: 'Cromos', link: 'https://www.elespectador.com/cromos/'},
        {name: 'Revista Vea', link: 'https://www.elespectador.com/revista-vea/'},
    ];

    export const footerSections = (images) => {
        return [
            {name: 'Opinión', link: 'https://www.elespectador.com/opinion/' },
            {name: 'Judicial', link: 'https://www.elespectador.com/judicial/' },
            {name: 'Política', link: 'https://www.elespectador.com/politica/' },
            {name: 'Investigación', link: 'https://www.elespectador.com/investigacion/' },
            {name: 'Colombia', link: 'https://www.elespectador.com/colombia/' },
            {name: 'Bogotá', link: 'https://www.elespectador.com/bogota/' },
            {name: 'Mundo', link: 'https://www.elespectador.com/mundo/' },
            {name: 'Economía', link: 'https://www.elespectador.com/economia/' },
            {name: 'Tecnología', link: 'https://www.elespectador.com/tecnologia/' },
            {name: 'Ciencia', link: 'https://www.elespectador.com/ciencia/' },
            {name: 'Ambiente', link: 'https://www.elespectador.com/ambiente/' },
            {name: 'Salud', link: 'https://www.elespectador.com/salud/' },
            {name: 'Educación', link: 'https://www.elespectador.com/educacion/' },
            {name: 'Entretenimiento', link: 'https://www.elespectador.com/entretenimiento/' },
            {name: 'Deportes', link: 'https://www.elespectador.com/deportes/' },
            {name: 'Video', link: 'https://www.elespectador.com/video/' },
            {name: 'Especiales', link: 'https://www.elespectador.com/especiales/' },
            {name: 'Colecciones', link: 'https://www.elespectador.com/colecciones/' },
            {name: 'Contenido Patrocinado', link: 'https://www.elespectador.com/contenido-patrocinado/' },
            {name: 'Reportajes', link: 'https://www.elespectador.com/reportajes/' },
            {name: 'Historias Visuales', link: 'https://www.elespectador.com/historias-visuales/' },
            {name: 'Pasatiempos', link: 'https://pasatiempos.elespectador.com', outside: true },
            {name: 'Blogs', link: 'https://blogs.elespectador.com', outside: true },
            {name: 'Actualidad', link: 'https://www.elespectador.com/actualidad/' },
            {name: 'El Carrito', link: 'https://www.elespectador.com/el-carrito/' },
            {name: 'El magazín cultural', link: 'https://www.elespectador.com/el-magazin-cultural/' , gray: true, image: images['/el-magazin-cultural'].image, imageMobile: images['/el-magazin-cultural'].imageMobile},
            {name: 'Colombia +20', link: 'https://www.elespectador.com/colombia-20/' , gray: true, image: images['/colombia-20'].image, imageMobile: images['/colombia-20'].imageMobile},
            {name: 'Impacto Mujer', link: 'https://www.elespectador.com/impacto-mujer/' , gray: true, image: images['/impacto-mujer'].image, imageMobile: images['/impacto-mujer'].imageMobile},
            {name: 'Cromos', link: 'https://www.elespectador.com/cromos/' , gray: true, image: images['/cromos'].image, imageMobile: images['/cromos'].imageMobile},
            {name: 'Autos', link: 'https://www.elespectador.com/autos/' , gray: true, image: images['/autos'].image, imageMobile: images['/autos'].imageMobile},
            {name: 'Revista Vea', link: 'https://www.elespectador.com/revista-vea/' , gray: true, image: images['/revista-vea'].image, imageMobile: images['/revista-vea'].imageMobile},
            {name: 'Turismo', link: 'https://www.elespectador.com/turismo/' , gray: true, image: images['/turismo'].image, imageMobile: images['/turismo'].imageMobile},
            {name: 'Gastronomía y Recetas', link: 'https://www.elespectador.com/gastronomia-y-recetas/' , gray: true, image: images['/gastronomia-y-recetas'].image, imageMobile: images['/gastronomia-y-recetas'].imageMobile},
            {name: 'Desaparecidos', link: 'https://www.elespectador.com/desaparecidos-colombia/' , gray: true, image: images['/desaparecidos-colombia'].image, imageMobile: images['/desaparecidos-colombia'].imageMobile},
        ];
        };